"""Initial schema

Revision ID: 2e8a9d95107a
Revises: 
Create Date: 2026-01-21 15:50:54.461532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8a9d95107a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategorija_dogadjaja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naziv')
    )
    op.create_table('korisnik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=50), nullable=False),
    sa.Column('prezime', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('lozinka', sa.String(length=255), nullable=False),
    sa.Column('uloga', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dogadjaj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=100), nullable=False),
    sa.Column('opis', sa.Text(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('lokacija', sa.String(length=100), nullable=False),
    sa.Column('cena', sa.Float(), nullable=True),
    sa.Column('imageURL', sa.String(length=255), nullable=True),
    sa.Column('sourceURL', sa.String(length=255), nullable=True),
    sa.Column('kategorija_dogadjaja_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kategorija_dogadjaja_id'], ['kategorija_dogadjaja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privatni_dogadjaj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=100), nullable=False),
    sa.Column('opis', sa.Text(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('lokacija', sa.String(length=100), nullable=False),
    sa.Column('kapacitet', sa.Integer(), nullable=False),
    sa.Column('korisnik_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['korisnik_id'], ['korisnik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('omiljeni_dogadjaj',
    sa.Column('korisnik_id', sa.Integer(), nullable=False),
    sa.Column('dogadjaj_id', sa.Integer(), nullable=False),
    sa.Column('podsetnik', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['dogadjaj_id'], ['dogadjaj.id'], ),
    sa.ForeignKeyConstraint(['korisnik_id'], ['korisnik.id'], ),
    sa.PrimaryKeyConstraint('korisnik_id', 'dogadjaj_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('omiljeni_dogadjaj')
    op.drop_table('privatni_dogadjaj')
    op.drop_table('dogadjaj')
    op.drop_table('korisnik')
    op.drop_table('kategorija_dogadjaja')
    # ### end Alembic commands ###




